### ISSUE TITLE
brew nasm problem

### ISSUE THREAD

**Issue by vertexclique** [Arcterus/kRnel#4]
In mac os nasm acquired from brew hasn't got any elf64 option. There should be a fix for that from upstream or in code.

**Comment by Arcterus** [comment]
That's very odd.  My local version of `nasm`, which I installed with Homebrew, _does_ have the elf64 option.  Are you getting an error that says there is not elf64 option?

**Comment by pczarn** [comment]
Double check `nasm -v`. Make sure the version from brew is in the path.

**Comment by Arcterus** [comment]
@pczarn who are you referring to?

**Comment by pczarn** [comment]
@Arcterus: to @vertexclique

**Comment by Arcterus** [comment]
@pczarn just wanted to make sure :)

**Comment by vertexclique** [comment]
sorry it was my fault about preferred nasm. apple nasm doesnt have this idk why. brew has options.

**Comment by Arcterus** [comment]
It's fine.  Glad that it's working for you now. :smile:

**Comment by vertexclique** [comment]
I sent a mail to Arcterus@mail.com

2014-04-19 22:04 GMT+03:00 Arcterus notifications@github.com:

> It's fine. Glad that it's working for you now. [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Arcterus/kRnel/issues/4#issuecomment-40877835
> .

## 

Mahmut Bulut
